replicaCount: 1

ingressController: nginx

service:
  type: ClusterIP
  port: 5555

domainName: cdn.casty.local

image:
  repository: castyapp/cdn
  pullPolicy: Always
  tag: latest

tls:
  enabled: false
  email: 
  caServer: https://acme-v02.api.letsencrypt.org/directory
  cloudflare: 
    email: 
    token: 
  dnsNames:
    - cdn.casty.local

resources: {}
tolerations: {}

config:
  endpoint: ""
  access_key: ""
  secret_key: ""
  region: ""
  insecure_skip_verify: false
  use_https: true
  sentry_dsn: "sentry.dsn.here"
