replicaCount: 3

service:
  type: ClusterIP
  port: 55283

image:
  repository: castyapp/grpc
  pullPolicy: Always
  tag: latest

resources: {}
tolerations: {}

config:

  debug: true
  env: dev

  db:
    name: "casty"
    host: "localhost"
    port: 27017
    user: "root"
    pass: ""
    auth_source: ""

  redis:
    cluster: false
    masterName: mymaster
    sentinels:
    - "localhost:5000"
    addr: "localhost:5000"
    pass: a-very-complex-password-here
    sentinel_pass: a-very-complex-password-here

  jwt:
    access_token:
      expires_at:
        type: "days"
        value: 1
      secret: ""
    refresh_token:
      expires_at:
        type: "weeks"
        value: 1
      secret: ""

  s3:
    endpoint: ""
    access_key: ""
    secret_key: ""
    use_http: false
    insecure_skip_verify: false

  sentry:
    enabled: false
    dsn: ""

  recaptcha:
    enabled: false
    type: "hcaptcha"
    secret: ""

  oauth:
    registration_by_oauth: false
    spotify:
      enabled: false
      client_id: 
      client_secret: 
      redirect_uri: 
    google:
      enabled: false
      client_id: 
      client_secret: 
      redirect_uri: 
