apiVersion: v1
kind: Service
metadata:
  namespace: casty-grpc
  name: grpc
  labels:
    app: grpc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: grpc
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: 55283