{{ if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: casty-gateway
  name: cloudflare-gateway-token-secret
type: Opaque
stringData:
  api-token: {{ .Values.tls.cloudflare.token }}
{{ end }}