apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  config.hcl: |
  {{- with .Values.config }}

    # Debug mode
    debug = {{ .debug }}

    # Application environment
    env = "{{ .env }}"

    # Configure grpc client
    #
    # You can find more information about how to run grpc server 
    # is available here [https://github.com/castyapp/grpc.server#readme]
    grpc {
      host = "{{ .grpc.host }}"
      port = {{ .grpc.port | int }}
    }

    # Redis configurations
    redis {
      # if you wish to use redis cluster, set this value to true
      # If cluster is true, sentinels is required
      # If cluster is false, addr is required
      cluster = {{ .redis.cluster  }}
      master_name = "{{ .redis.masterName }}"
      {{- if (default .redis.cluster false) }}
      sentinels = {{ toJson .redis.sentinels }}
      sentinel_pass = "{{ .redis.sentinel_pass }}"
      {{- else }}
      addr = "{{ .redis.addr }}"
      {{- end }}
      pass = "{{ .redis.pass }}"
    }

    # Sentry config
    sentry {
      enabled = {{ .sentry.enabled }}
      dsn = "{{ .sentry.dsn }}"
    } 

  {{- end }}

