apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: casty-gateway
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
          "--ug-port",
          "3001",
          "--tg-port",
          "3002",
          "--config-file",
          "{{ .Values.configDirectory }}/config.yaml",
          "--env",
          "{{ .Values.appConfig.app.env }}"
        ]
        ports:
        - containerPort: 3001
          containerPort: 3002
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          - name: config-volume
            mountPath: {{ .Values.configDirectory }}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config-volume
        configMap:
          name: gateway-config
