apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
    group: casty
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
          "--ug-port",
          "3001",
          "--tg-port",
          "3002",
          "--config-file",
          "/config/config.hcl",
        ]
        ports:
        - containerPort: 3001
          containerPort: 3002
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 8 }}
        {{- end }}
        volumeMounts:
          - name: config-volume
            mountPath: /config
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config-volume
        configMap:
          name: gateway-config
