apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: casty-gateway
  name: casty-gateway-ingress
  labels:
    app: gateway
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressController }}
    nginx.org/websocket-services: gateway-service
spec:
  {{ if .Values.tls.enabled }}
  tls:
  - hosts:
      {{- toYaml .Values.tls.dnsNames | nindent 12 }}
    secretName: casty-gateway-lets-encrypt-tls
  {{ end }}
  rules:
    - host: {{ .Values.userGatewayDomain }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: gateway-service
              port: 
                number: {{ .Values.service.ports.userGateway }}
    - host: {{ .Values.theaterGatewayDomain }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: gateway-service
              port: 
                number: {{ .Values.service.ports.theaterGateway }}
