{{ if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: casty-api
  name: casty-api-lets-encrypt
  labels:
    app: dash
spec:
  secretName: casty-api-lets-encrypt-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
    {{- toYaml .Values.tls.dnsNames | nindent 12 }}
  privateKey:
    rotationPolicy: Always
{{ end }}