{{ if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: casty-api
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: {{ .Values.tls.cloudflare.token }}
{{ end }}