apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: casty-api
  name: api-deploy
  labels:
    app: api
    group: casty
spec:
  selector:
    matchLabels:
      app: api
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
          "--port",
          "9002",
          "--config-file",
          "{{ .Values.configDirectory }}/config.yml",
        ]
        ports:
        - containerPort: 9002
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: "{{ .Values.configDirectory }}/config.yml"
          subPath: "config.yml"
          readOnly: false
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: api-config
