apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9002
