apiVersion: v1
kind: ConfigMap
metadata:
  name: cdn-config
data:
  config.hcl: |
  {{- with .Values.config }}
    endpoint             = "{{ .s3.endpoint }}"
    access_key           = "{{ .s3.access_key }}"
    secret_key           = "{{ .s3.secret_key }}"
    use_https            = {{ .s3.use_https }}
    region               = {{ .s3.region }}
    insecure_skip_verify = {{ .s3.insecure_skip_verify }}
    sentry_dsn           = "sentry.dsn.here"
  {{- end }}
