apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-deploy
  labels:
    app: cdn
    group: casty
spec:
  selector:
    matchLabels:
      app: cdn
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cdn
    spec:
      containers:
      - name: cdn
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
          "--port",
          "5555",
          "--config-file",
          "/config/config.hcl",
        ]
        ports:
        - containerPort: 5555
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 8 }}
        {{- end }}
        volumeMounts:
          - name: config-volume
            mountPath: /config
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: cdn-config
