apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: casty-cdn
  name: casty-cdn-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressController }}
spec:
  {{ if .Values.tls.enabled }}
  tls:
  - hosts:
      {{- toYaml .Values.tls.dnsNames | nindent 12 }}
    secretName: casty-cdn-lets-encrypt-tls
  {{ end }}
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: cdn-service
              port: 
                number: 5555
