apiVersion: v1
kind: Service
metadata:
  namespace: casty-cdn
  name: cdn-service
  labels:
    app: cdn
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cdn
  ports:
    - name: cdn
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5555
