replicaCount: 3

ingressController: nginx

service:
  type: ClusterIP
  port: 9002

domainName: api.casty.local

image:
  repository: castyapp/api
  pullPolicy: Always
  tag: latest

tls:
  enabled: false
  email: 
  caServer: https://acme-v02.api.letsencrypt.org/directory
  cloudflare: 
    email: 
    token: 
  dnsNames:
    - api.casty.local

resources: {}
tolerations: {}

config:
  debug: true
  metrics: false
  env: dev
  timezone: "America/California"
  grpc:
    host: localhost
    port: 55283
  http:
    access_control_allow_origin: "*"
  s3:
    endpoint: ""
    access_key: ""
    secret_key: ""
    insecure_skip_verify: false
    use_https: true
  sentry:
    enabled: false
    dsn: "sentry.dsn.here"
  recaptcha:
    enabled: false
    type: "hcaptcha"
    secret: "super-secure-captcha-secret-here"
